### ISSUE TITLE
grpc.aio._call.AioRpcError

### ISSUE THREAD

**Issue by amiwrpremium** [InjectiveLabs/sdk-python#123]
I was trying to use [exchange client example](https://github.com/InjectiveLabs/sdk-python/blob/master/examples/exchange_client/spot_exchange_rpc/2_Markets.py) but I ran into the error below:

```chain session cookie loaded from disk: 
E0624 16:31:01.217773000 6155677696 hpack_parser.cc:1234]              Error parsing metadata: error=invalid value key=content-type value=text/html
Traceback (most recent call last):
  File "/Users/amiwr/Code/Python/Nice_Team/Injective_Test/test.py", line 39, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/amiwr/Code/Python/Nice_Team/Injective_Test/test.py", line 29, in main
    market = await client.get_spot_markets(
  File "/Users/amiwr/Code/Python/Nice_Team/Injective_Test/venv/lib/python3.9/site-packages/pyinjective/async_client.py", line 557, in get_spot_markets
    return await self.stubSpotExchange.Markets(req)
  File "/Users/amiwr/Code/Python/Nice_Team/Injective_Test/venv/lib/python3.9/site-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "{"created":"@1656072061.217971000","description":"Error received from peer ipv4:34.138.231.254:443","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"Stream removed","grpc_status":2}"
>```

**Comment by achilleas-kal** [comment]
K8S on testnet is under maintenance, you can use an explicit sentry for the time being.

> import asyncio
> import logging
> 
> from pyinjective.async_client import AsyncClient
> from pyinjective.constant import Network
> 
> async def main() -> None:
>     network = Network.testnet(node="sentry0")
>     client = AsyncClient(network, insecure=True)
>     market_status = "active"  # active, paused, suspended, demolished or expired
>     base_denom = "inj"
>     quote_denom = "peggy0xdAC17F958D2ee523a2206206994597C13D831ec7"
>     market = await client.get_spot_markets(
>         market_status=market_status,
>         base_denom=base_denom,
>         quote_denom=quote_denom
>     )
>     print(market)
> 
> 
> if __name__ == '__main__':
>     logging.basicConfig(level=logging.INFO)
>     asyncio.get_event_loop().run_until_complete(main())
