### ISSUE TITLE
TypeError: Parameter to MergeFrom() must be instance of same class: expected injective.exchange.v1beta1.exchange_pb2.SpotOrder got injective.exchange.v1beta1.exchange_pb2.SpotOrder.

### ISSUE THREAD

**Issue by amiwrpremium** [InjectiveLabs/sdk-python#127]
I tried to run [this example](https://github.com/InjectiveLabs/sdk-python/blob/master/examples/chain_client/4_MsgCreateSpotMarketOrder.py) to create a spot order but I've encountered error below:

`TypeError: Parameter to MergeFrom() must be instance of same class: expected injective.exchange.v1beta1.exchange_pb2.SpotOrder got injective.exchange.v1beta1.exchange_pb2.SpotOrder. for field MsgCreateSpotLimitOrder.order
`

I used the "sentry0" mainnet (`client = AsyncClient(Network.mainnet('sentry0'), insecure=True)`)

**Comment by achilleas-kal** [comment]
Are you using a Mac or is that on Linux?

**Comment by amiwrpremium** [comment]
I'm using Mac OS Monterey with an Apple silicon chip

Python 3.9.9
injective-py==0.5.6.8

**Comment by achilleas-kal** [comment]
Can you try:
1) Installing python through brew and not pyenv
2) Running `brew unlink protobuf && brew link protobuf
`
I encountered this issue before on my own mac and was solved through these steps.

**Comment by achilleas-kal** [comment]
This was fixed through the steps provided above through a direct discussion on Telegram with @amiwrpremium
