### ISSUE TITLE
swap token 

### ISSUE THREAD

**Issue by Arthur17vtg** [InjectiveLabs/sdk-python#282]
Hello, I'm a beginner programmer here. I'd like to swap INJ to token A using a python script, and I can't figure how to do. 

Could you provide me some help please? 

Thanks

**Comment by aarmoa** [comment]
Swaps are not supported by Injective chain natively. You will need to execute it through the smart contract of any of the dApps providing the feature. You can check the examples on MsgExecuteContract or MsgExecuteContractCompat to see how to interact with smart contracts
