### ISSUE TITLE
None of the mainnet configs work

### ISSUE THREAD

**Issue by followprotocol** [InjectiveLabs/sdk-python#297]
everything works just fine on testnet, whenever switched to mainnet i get the following

`AioRpcError SSL_ERROR_SSL:Error parsing 'content-type' metadata: error=invalid `

tried lb, sentry0 and sentry3
none of them work

**Comment by aarmoa** [comment]
What SDK version are you using? `sentry0` and `sentry3` are no longer supported by the SDK. If you were able to try with them, you are using an old version
