### ISSUE TITLE
missing dependency bip32

### ISSUE THREAD

**Issue by DrunkRandomWalker** [InjectiveLabs/sdk-python#30]

**Comment by Qiu-INJ** [comment]
try `pip install bip32`

**Comment by achilleas-kal** [comment]
We should add this in the Pipfile so that it's installed along with the other dependencies https://github.com/InjectiveLabs/sdk-python/blob/master/Pipfile and re-publish the pkg.

**Comment by achilleas-kal** [comment]
Closed by https://github.com/InjectiveLabs/sdk-python/pull/31/commits/caef4937d8df71832a1e860aa3b4e315b1ba3d35
