### ISSUE TITLE
3rd Party RPC 

### ISSUE THREAD

**Issue by sherlock-tez** [InjectiveLabs/sdk-python#303]
What config should I use when I want to use other RPC. For example: 
https://injective-rpc.publicnode.com/

injective-grpc.publicnode.com:443

When I use this code

`lcd_endpoint = "https://injective-rest.publicnode.com"
            tm_websocket_endpoint = "wss://injective-rpc.publicnode.com:443/websocket"
            grpc_endpoint = "injective-grpc.publicnode.com:443"
            grpc_exchange_endpoint = "sentry.exchange.grpc.injective.network:443"
            grpc_explorer_endpoint = "sentry.explorer.grpc.injective.network:443"
            cookie_assistant = BareMetalLoadBalancedCookieAssistant()
            use_secure_connection = True`

It errors: Error fetching chain cookie (Metadata(()))

**Comment by aarmoa** [comment]
You should check that with each RPC provider. Configuration will be different for each of them
