### ISSUE TITLE
make gen tries to clone non-existent repo

### ISSUE THREAD

**Issue by alexandru-g** [InjectiveLabs/sdk-python#329]
Running `make gen` as per the instructions fails when trying to clone https://github.com/InjectiveLabs/injective-core.git (which does not exist).

**Comment by aarmoa** [comment]
Please read the README.md carefully. That instruction you mention (make gen) is in the "Development" section, and is intended only for the SDK developers

**Comment by alex-btl** [comment]
@aarmoa a bit quick to jump to conclusions. I think development instructions should also be kept up to date and functional.

In our case, we needed to add support for parsing a message type that wasn't supported by python-sdk. I think that falls under development. But we managed to do so without following the development steps in the readme, thank you.
