### ISSUE TITLE
create tests

### ISSUE THREAD

**Issue by DrunkRandomWalker** [InjectiveLabs/sdk-python#6]
need some test cases or use examples are test cases

**Comment by achilleas-kal** [comment]
**Goal**
The aim of this [repo ](https://github.com/InjectiveLabs/sdk-python/tree/master/compatibility-tests)was to test all python versions from 3.7.0 to 3.9.6 for compatibility with the current codebase. Given that the support for python 3.6 ends in December 2021, this script tests versions 3.7 and above. Tests for functionality are already done by **make test** in injective-exchange and are continuously updated, thus there was no need to test the correct functionality of all messages and requests but only compatibility with the aforementioned python versions.

**Files**

1. run.sh
 A) Downloads all python versions and extracts the contents
 B) Opens a subshell and installs python
 C) Installs all the dependencies used by the Injective Exchange API and Chain Client
 D) Saves the python version and the stdout/stderr of the tests.py script to the results.txt file to have both successful and error output.
 E) Purges python and all its dependencies, repeats until the last version.

 2. tests.py
This python script imports all the libraries used by the Injective Exchange API and Chain Client. It makes a gRPC request and uses the data to broadcast a transaction to the chain with both cosmos-sdk and exchange messages using a REST API endpoint. Certain libraries are imported from injective-py which you can find [here](https://pypi.org/project/injective-py/)

 3. results.txt
This file contains the python version for each run and the output of test.py.

**Results**

Evidently, all the libraries are compatible with python 3.7.0 up to 3.9.6 as per the results.txt file

**Modifications for compatibility in Python 3.7**
Python 3.7 requires one small modification in _typings.py to be compatible with the codebase.

File: chain_client/_typings.py
Current codebase: **from typing import Literal, TypedDict**
Change to: **from typing_extensions import Literal, TypedDict**

API users must also install the library by running _pip3 install typing_extensions_

The Python 3.7 stdlib has an older version of typing.py so the above change in the code will fix the compatibility issue by importing Literal from typing_extensions
