### ISSUE TITLE
Add secure private key management with keyring

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/sdk-python#93]
Hey @xlab, creating this issue so we can look into adding this feature in sdk-python as it's only compatible for Golang-based bots now.

**Comment by xlab** [comment]
Kinds standard way to manage the encrypted secrets in Python https://pypi.org/project/keyring/
(with https://pypi.org/project/keyrings.cryptfile/ plugin to support plain files)

**Comment by aarmoa** [comment]
Closing this Issue because `keyrings.cryptfile` does not work. It is not compatible with the encryption method the cosmos Keyring uses. Decrypting the values would require the use of JOSE (JSON Object Siigning and Encryption)
